# Generated by Django 2.2.4 on 2022-04-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_Reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logreg',
            name='email',
            field=models.CharField(default='hana78@gmail.com', max_length=50),
        ),
    ]
