# Generated by Django 2.2.4 on 2022-04-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV_Show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default='This is Nice Show', max_length=500),
        ),
    ]
