# Generated by Django 2.2.4 on 2022-04-08 21:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('TV_Show', '0002_show_desc'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='show',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
