# Generated by Django 2.2.4 on 2022-04-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TV_Show', '0003_auto_20220409_0030'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='show',
            managers=[
            ],
        ),
    ]
