# Generated by Django 2.2.4 on 2022-04-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='Majed_Assg', max_length=45),
            preserve_default=True,
        ),
    ]
