# Generated by Django 2.2.4 on 2022-04-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0003_auto_20220402_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='Majed_Assg', max_length=45),
        ),
    ]
