# Generated by Django 2.2.4 on 2022-04-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fav_Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Busers',
            field=models.ManyToManyField(related_name='fusers', to='Fav_Books.User'),
        ),
    ]
